openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/jammacn/jm-passport-weapp/1.0.0
info:
  version: "1.0.0"
  title: jm-passport-weapp-api
  description: 通行证系统API(微信小程序)
paths:
  /login:
    post:
      responses:
        '200':
          description: 登陆成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenInfo'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginInfo'
  /login/{openid}:
    post:
      parameters:
        - name: openid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 登陆成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenInfo'
  /isbind/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 是否绑定了账户
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BindInfo'
  /isbinded/{bindId}:
    get:
      parameters:
        - name: bindId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 是否被绑定
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BindInfo'
  /bind/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: bindId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 绑定
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BindInfo'
  /unbind/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 解除绑定
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BindInfo'
components:
  schemas:
    LoginInfo:
      type: object
      properties:
        code:
          type: string
        iv:
          type: string
        encryptedData:
          type: string
      description: 登陆信息
    TokenInfo:
      type: object
      properties:
        id:
          type: string
          example: '596d5cb3baeeaf00203de4ec'
        token:
          type: string
          example: '3a90dd3a53914eae857793297738574a85ae74e5914fce723b9dc82d562a31cf'
        expire:
          type: integer
          format: int32
          example: 3600
        time:
          type: integer
          format: int64
          example: 1524634308844
      description: Token信息
    BindInfo:
      type: object
      properties:
        id:
          type: string
          example: '596d5cb3baeeaf00203de4ec'
        bindId:
          type: string
          example: '596d5cb3baeeaf00203deabc'
      description: 账户绑定信息
